oneprojectorg/common

apps/app/src/components/DiscussionModal/index.tsx
apps/app/src/components/PostFeed/DeletePost.tsx
apps/app/src/components/PostFeed/index.tsx
apps/app/src/components/PostUpdate/index.tsx
apps/app/src/utils/queryKeys.ts

This updates the Discussion Modal comment listing to handle optimistic updates better. It also optimizes the query so that there is no flashing during a re-render of all comments.

Discussion Modal Optimistic Updates

---

apps/app/src/components/CoCModal/index.tsx
apps/app/src/components/DiscussionModal/index.tsx
apps/app/src/components/InviteUserModal/index.tsx
apps/app/src/components/PrivacyPolicyModal/index.tsx
apps/app/src/components/Profile/ProfileDetails/AddRelationshipForm.tsx
apps/app/src/components/Profile/ProfileDetails/FundingRoleModal.tsx
apps/app/src/components/Profile/ProfileDetails/RemoveRelationshipModal.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateOrganizationForm.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateOrganizationModal.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateProfileForm.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateProfileModal.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateUserProfileModal.tsx
apps/app/src/components/ToSModal/index.tsx
packages/ui/src/components/Modal.tsx

Updates the Modals currently in use to the new consistent design

Update Modals to new design

---

apps/app/src/components/DiscussionModal/index.tsx
apps/app/src/components/PostFeed/index.tsx
apps/app/src/components/PostUpdate/index.tsx
apps/app/src/components/Profile/ProfileFeed/index.tsx
apps/app/src/components/screens/LandingScreen/Feed.tsx
apps/app/src/utils/optimisticUpdates.ts
packages/common/src/services/posts/getPosts.ts
packages/common/src/services/posts/listPosts.ts
packages/common/src/services/posts/listRelatedOrganizationPosts.ts
packages/ui/src/components/ReactionTooltip.tsx
packages/ui/src/components/ReactionsButton.tsx
packages/ui/src/index.ts
services/api/src/encoders/posts.ts

Adds a tooltip indicating who has reacted to the post.

Reaction Tooltip

---

apps/app/src/components/ErrorBoundary.tsx
apps/app/src/components/InviteUserModal/InviteToExistingOrganization.tsx
apps/app/src/components/InviteUserModal/index.tsx
packages/common/src/services/access/getRoles.ts
packages/common/src/services/access/index.ts
packages/common/src/services/email/index.ts
packages/common/src/services/organization/inviteUsers.ts
packages/common/src/services/organization/joinOrganization.ts
packages/common/src/services/user/index.ts
services/api/src/routers/organization/getRoles.ts
services/api/src/routers/organization/index.ts
services/api/src/routers/organization/inviteUser.ts
services/api/src/test/integration/README.md
services/api/src/test/integration/invite-trpc.integration.test.ts
services/api/src/test/integration/invite.integration.test.ts
services/api/src/test/integration/role-id.integration.test.ts
services/db/seedData/AccessRoles.sql

Invite User With Roles

---

apps/app/package.json
apps/app/src/utils/UserProvider.tsx
packages/common/src/services/user/index.ts
pnpm-lock.yaml
services/api/package.json
services/api/src/encoders/users.ts
services/api/src/routers/account/getMyAccount.ts
services/api/src/routers/account/switchProfile.ts
services/api/src/routers/organization/inviteUser.ts
services/api/src/routers/organization/joinOrganization.ts
services/cache/kv.ts

Exposes boolean permission on the frontend for permissions on specific profiles/organizations.

Pass Org User Permissions to Frontend

---

packages/ui/src/components/Select.tsx
packages/ui/stories/Select.stories.tsx

Adding "pill" Select variant

---

services/db/migrations/0004_charming_malcolm_colcord.sql
services/db/migrations/meta/0004_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/publicTables.ts
services/db/schema/tables/relationships.sql.ts

This adds in the tables needed for more generic relationships between profiles

Add in new relationships table for generic relationships

---

services/db/migrations/0005_soft_overlord.sql
services/db/migrations/meta/0005_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/publicTables.ts
services/db/schema/tables/decisionProcesses.sql.ts
services/db/schema/tables/decisions.sql.ts
services/db/schema/tables/entities.sql.ts
services/db/schema/tables/posts.sql.ts
services/db/schema/tables/processInstances.sql.ts
services/db/schema/tables/profiles.sql.ts
services/db/schema/tables/proposals.sql.ts
services/db/schema/tables/stateTransitionHistory.sql.ts

Adds in table for decision making

Add Decision Making Tables

---

apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/page.tsx
apps/app/src/components/decisions/ProposalEditor.tsx
apps/app/src/components/decisions/ProposalsList.tsx
packages/common/src/services/decision/__tests__/authorization.test.ts
packages/common/src/services/decision/__tests__/categoryFlowIntegration.test.ts
packages/common/src/services/decision/__tests__/createProcessWithCategories.test.ts
packages/common/src/services/decision/__tests__/listProposals.test.ts
packages/common/src/services/decision/createProcess.ts
packages/common/src/services/decision/createProposal.ts
packages/common/src/services/decision/getProcessCategories.ts
packages/common/src/services/decision/index.ts
packages/common/src/services/decision/listProposals.ts
packages/common/src/services/decision/updateProposal.ts
packages/common/src/test/setup.ts
services/api/src/encoders/decision.ts
services/api/src/routers/decision/instances/getCategories.ts
services/api/src/routers/decision/instances/index.ts
services/db/migrations/0006_superb_prodigy.sql
services/db/migrations/meta/0006_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/tables/proposals.sql.ts
services/db/schema/tables/taxonomies.sql.ts

Adds in filtering for categories into the proposal listing

Process Categories for Proposals

---

apps/app/src/components/Profile/ProfileDetails/UpdateUserProfileModal.tsx

Fixes the close button on the Edit Profile modal not closing

Fix closing of Edit Profile modal

---

apps/app/src/components/Profile/ProfileContent/DecisionsTabs.tsx
apps/app/src/components/Profile/ProfileContent/MembersList.tsx
apps/app/src/components/Profile/ProfileContent/index.tsx
apps/app/src/components/RelationshipList/index.tsx
apps/app/src/components/screens/Profile/index.tsx
apps/app/src/components/screens/ProfileRelationships/index.tsx
packages/common/src/services/organization/getOrganizationUsers.ts
packages/common/src/services/organization/index.ts
services/api/src/routers/organization/index.ts
services/api/src/routers/organization/listUsers.ts
services/api/src/test/integration/listUsers.integration.test.ts

Adds an endpoint as well as a tab for organization pages displaying all members of an organization and their roles

List members for admins

---

apps/app/src/components/DiscussionModal/index.tsx
apps/app/src/components/PostUpdate/index.tsx
packages/common/src/services/posts/createPostInOrganization.ts
packages/common/src/services/posts/getPosts.ts

Quick-fixes PostUpdates and comments (which is awaiting a refactor).

PostUpdate fix

---

apps/app/src/components/RichTextEditor/RichTextEditorFloatingToolbar.tsx
apps/app/src/components/decisions/ProposalEditor.tsx
apps/app/src/components/decisions/ProposalRichTextToolbar.tsx
apps/app/src/hooks/useProposalFileUpload.ts
apps/app/src/utils/proposalContentProcessor.ts
packages/common/src/services/decision/createProposal.test.ts
packages/common/src/services/decision/createProposal.ts
packages/common/src/services/decision/proposalContentProcessor.test.ts
packages/common/src/services/decision/proposalContentProcessor.ts
services/api/src/encoders/decision.ts
services/api/src/routers/decision/index.ts
services/api/src/routers/decision/uploadProposalAttachment.test.ts
services/api/src/routers/decision/uploadProposalAttachment.ts
services/db/migrations/0007_tired_vulture.sql
services/db/migrations/meta/0007_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/publicTables.ts
services/db/schema/tables/attachments.sql.ts
services/db/schema/tables/proposalAttachments.sql.ts
services/db/schema/tables/proposals.sql.ts

- Enable file uploads in Proposal Rich Text fields

Release: Images in Proposals

---

CLAUDE.md
apps/app/src/components/decisions/ProposalsList.tsx
packages/common/src/services/decision/listProposals.ts
services/api/src/encoders/decision.ts

This adds in the ability to filter by your own proposals as well as sort proposals. It also fixes wrapping for the Selects (especially when they are translated)

Proposal Filters and Styling

---

apps/app/src/components/decisions/ProposalCard.tsx
packages/common/src/services/access/index.ts
packages/common/src/services/decision/createProposal.ts
packages/common/src/services/decision/listProposals.ts
services/api/src/routers/decision/proposals/create.ts

- **Updating permissions in create Proposal**
- **Include avatar images in proposal cards**

Submit Proposal from Org, Fix Avatar Image in Proposal Cards

---

apps/app/src/components/decisions/ProposalCard.tsx
apps/app/src/components/decisions/ProposalEditor.tsx
packages/ui/src/components/Button.tsx
services/db/migrations/0008_gray_ronan.sql
services/db/migrations/meta/0008_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/tables/organizations.sql.ts
services/db/schema/tables/posts.sql.ts
services/db/schema/tables/profiles.sql.ts
services/db/schema/tables/users.sql.ts

- Implement proposal filtering by process and status
- Update access control system for proposal operations
- Update UI components
- Add database migrations for new indexes

Release: Add proposal filtering system, DB indexes

---

apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/proposal/[proposalId]/edit/page.tsx
apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/proposal/[proposalId]/page.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/CustomWidgets.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/index.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/schemas/simple.ts
apps/app/src/components/Profile/ProfileContent/DecisionsTabs.tsx
apps/app/src/components/Profile/ProfileContent/index.tsx
apps/app/src/components/RichTextEditor/RichTextEditor.tsx
apps/app/src/components/RichTextEditor/RichTextEditorContent.tsx
apps/app/src/components/RichTextEditor/RichTextEditorToolbar.tsx
apps/app/src/components/decisions/ProposalEditor.tsx
apps/app/src/components/decisions/ProposalView.tsx
apps/app/src/components/decisions/ProposalViewLayout.tsx
apps/app/src/hooks/useFeatureFlag.ts
packages/ui/src/components/Select.tsx

- Add error toasts during phase validation
- Update RichText styles for custom fields
- Move mutations to client side and associated queries for proper invalidation

Release: Decision Making updates

---

packages/common/src/services/organization/joinOrganization.ts
services/api/src/test/integration/invite.integration.test.ts
services/api/src/test/integration/role-id.integration.test.ts

This avoids setting the currentProfile to an org that a user is not an admin for.

Set currentProfile for non-admins

---

services/db/migrations/0009_stiff_warbound.sql
services/db/migrations/meta/0009_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/publicTables.ts
services/db/schema/tables/modules.sql.ts
services/db/schema/tables/profiles.sql.ts

Add in tables for enabling modules per profile

Module Tables

---

apps/app/src/components/Profile/ProfileContent/DecisionsTabs.tsx
apps/app/src/components/Profile/ProfileContent/IndividualTabs.tsx
apps/app/src/components/Profile/ProfileContent/index.tsx
apps/app/src/components/SiteHeader/index.tsx
apps/app/src/components/screens/Profile/index.tsx
apps/app/src/utils/modules.ts
packages/common/src/services/organization/getOrganization.ts
packages/common/src/services/profile/getProfile.ts
services/api/src/encoders/index.ts
services/api/src/encoders/modules.ts
services/api/src/encoders/profiles.ts
services/api/src/encoders/users.ts
services/api/src/routers/organization/getOrganization.ts
services/api/src/routers/profile/getProfile.ts

Resolves enabled modules in the API for profiles and checks for the decisions module when displaying on profiles

Resolve Modules for Profiles

---

apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/page.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/index.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/schemas/simple.ts
apps/app/src/components/Profile/ProfileDecisions/index.tsx
apps/app/src/components/decisions/CurrentPhaseSurface.tsx
apps/app/src/components/decisions/DecisionInstanceContent.tsx
apps/app/src/components/decisions/DecisionStats.tsx
apps/app/src/utils/decisionProcessTransforms.ts
packages/common/src/services/decision/getInstance.ts
packages/common/src/services/decision/types.ts
services/api/src/encoders/decision.ts

This allows users to optionally hide budgets from members and to later show them.

Allow hiding of budgets

---

apps/app/src/components/InviteSuccessModal/index.tsx
apps/app/src/components/InviteUserModal/index.tsx
packages/common/src/services/email/index.ts
packages/common/src/services/organization/inviteUsers.ts
pnpm-lock.yaml
services/emails/index.tsx
services/emails/package.json

- Support batch emails
- Allow pasting of emails into modal
- Validate at 100 emails, split emails before validation

Batch Emails, Email Splitting

---

apps/app/src/components/PostUpdate/index.tsx
apps/app/src/components/decisions/ProcessViewTracker.tsx
apps/app/src/components/decisions/ProposalView.tsx
packages/analytics/src/utils.ts
packages/types/src/posts.ts
services/api/src/routers/decision/instances/getInstance.ts
services/api/src/routers/decision/proposals/create.ts
services/api/src/routers/decision/proposals/get.ts
services/api/src/routers/posts/createPost.ts
services/api/src/routers/profile/relationships.ts

- Analytics for Decisions (#163)

Release: Analytics for Decision Making

---

packages/common/package.json
packages/common/src/services/access/index.ts
packages/common/src/services/organization/deleteOrganizationUser.ts
packages/common/src/services/organization/updateOrganizationUser.ts
pnpm-lock.yaml
services/cache/kv.ts

This caches the orgUser which is frequently accessed across many endpoints

Cache orgUser

---

apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/page.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/index.tsx
apps/app/src/components/Profile/CreateDecisionProcessModal/schemas/horizon.ts
apps/app/src/components/Profile/CreateDecisionProcessModal/schemas/schemaLoader.ts
apps/app/src/components/Profile/EditDecisionProcessModal/index.tsx
apps/app/src/components/Profile/ProfileDecisions/index.tsx
apps/app/src/components/decisions/DecisionInstanceContent.tsx
apps/app/src/components/screens/Profile/index.tsx
apps/app/src/utils/decisionProcessTransforms.ts

Release: Horizon Schema

---

apps/app/src/components/PostFeed/index.tsx
apps/app/src/components/decisions/ProposalCard.tsx
apps/app/src/components/decisions/ProposalCardMenu.tsx
apps/app/src/components/decisions/ProposalsList.tsx
apps/app/src/utils/proposalUtils.ts
packages/common/src/services/decision/__tests__/updateProposalStatus.test.ts
packages/common/src/services/decision/index.ts
packages/common/src/services/decision/listProposals.ts
packages/common/src/services/decision/updateProposal.ts
packages/common/src/services/decision/updateProposalStatus.ts
packages/ui/package.json
packages/ui/src/components/OptionMenu.tsx
packages/ui/src/components/Select.tsx
packages/ui/src/index.ts
services/api/src/encoders/decision.ts
services/api/src/encoders/index.ts
services/api/src/routers/decision/proposals/index.ts
services/api/src/routers/decision/proposals/updateStatus.test.ts
services/api/src/routers/decision/proposals/updateStatus.ts
services/db/migrations/0014_hard_sue_storm.sql
services/db/migrations/meta/0014_snapshot.json
services/db/migrations/meta/_journal.json
services/db/schema/tables/proposals.sql.ts

Adds shortlisting for proposals by admins as well as filtering by those shortlists.

Shortlist Proposals

---

apps/app/src/components/PostUpdate/index.tsx
apps/app/src/components/decisions/ProposalCard.tsx
apps/app/src/components/decisions/ProposalView.tsx
packages/common/src/services/decision/getProposal.ts
packages/common/src/services/decision/listProposals.ts
packages/common/src/services/posts/createPost.ts
services/api/src/encoders/decision.ts

- **Add comment counts**
- **invalidate and count comments**

Comment Counts and Invalidations

---

apps/app/src/app/[locale]/(no-header)/profile/[slug]/decisions/[id]/page.tsx
apps/app/src/components/Bullet/index.tsx
apps/app/src/components/Profile/ProfileDetails/UpdateProfileModal.tsx
apps/app/src/components/ToSModal/index.tsx
apps/app/src/components/decisions/DecisionInstanceContent.tsx
apps/app/src/components/decisions/DecisionInstanceHeader.tsx
apps/app/src/components/decisions/ProposalCard.tsx
apps/app/src/components/decisions/ProposalCardActions.tsx
apps/app/src/components/decisions/ProposalCardMenu.tsx
apps/app/src/components/decisions/ProposalViewLayout.tsx
apps/app/src/components/decisions/ProposalsList.tsx
apps/app/src/components/decisions/layout.tsx
apps/app/src/components/decisions/types.ts
apps/app/src/lib/i18n/dictionaries/en.json
apps/app/src/lib/i18n/dictionaries/es.json
apps/app/src/lib/i18n/dictionaries/fr.json
apps/app/src/lib/i18n/dictionaries/pt.json
packages/ui/package.json
packages/ui/src/components/Dialog.tsx
packages/ui/src/components/GrowingFacePile/index.tsx
packages/ui/src/components/Modal.tsx
packages/ui/src/components/OptionMenu.tsx
packages/ui/src/index.ts

- **refactoring, restyling proposal page**
- **Fix dismissable modal**
- **Use basic dismissable modal**
- **Move actions to top of page in decision page, fix modal dismissable**
- **Use grid in proposal list**
- **show not shortlisted status, sizings on cards**
- **Updating styles**
- **Show shortlisting conditionally in menu with Delete**
- **Add GrowingFacePile**

New Proposal Layout

---

apps/app/src/components/decisions/ProposalsList.tsx
apps/app/src/components/decisions/useProposalFilters.ts

Adds filters to the url in decisions so the back button will work correctly when viewing proposals.

Add Filter State in Decisions to URL
